### ISSUE TITLE
does this still work

### ISSUE THREAD

**Issue by gregnetau** [genzdev/aws-codepipeline-discord-integration-terraform-module#2]
Hello & thanks for your work on this module. I've given it a go to test deployment notifications for our 4 codepipeline jobs however sadly we never get any notifications. 

When i try and manually test a notification from Lambda, i get the following error:

`ERROR	Invoke Error 	{"errorType":"TypeError","errorMessage":"Cannot read property 'action' of undefined","stack":["TypeError: Cannot read property 'action' of undefined","    at processEvent (/var/task/handler.js:11:20)","    at Runtime.exports.handle [as handler] (/var/task/handler.js:21:3)","    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"]}`

Does this require more work?

**Comment by genzdev** [comment]
Hey @gregnetau, this module is fully functional, here is an example implementation:

```
module "cicd_web_discord" {
  source            = "github.com/genzdev/aws-codepipeline-discord-integration-terraform-module.git"
  PIPELINE_NAMES    = ["<valid_aws_codepipeline_resource_name>"]
  APP_NAME          = "<valid_aws_codepipeline_resource_name>"
  DISCORD_WEBHOOK_URL = "https://discord.com/api/webhooks/<channel_webhook_string>"
  DISCORD_CHANNEL     = "your_bot_name"
  REGION            = "us-east-1"
}
```

From the error message you posted, I can't really tell what went wrong (since you did a manual test, please post the `event` payload that was sent to the lambda during the test).

Please post more information like:
1. Your module implementation code
2. Codepipeline resource AWS region vs Discord Module's specified AWS region.
3. `event` parameter content received by the lambda's handler function from when a job was executed & you didn't receive a notification.
4. Discord module's lambda runtime execution log (should be available in cloudwatch logs).

The more info you share the easier it will be for me to help you debug this.
